name: test

on:
  push:
    paths:
      - ".github/workflows/*"
      - "CMakeLists.txt"
      - "includes/**"
      - "src/**"
      - "test/**"

  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/*"
      - "CMakeLists.txt"
      - "includes/**"
      - "src/**"
      - "test/**"

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mmv
        uses: actions/checkout@v3

      - name: Build test executables
        run: cmake -Bbuild -DTESTING=ON && cmake --build ./build

      - name: Clean up test executable
        run: rm -rf ./build/*
